#!/usr/bin/env bash
# GitHub Pages 정적 배포 — public/ 을 gh-pages 브랜치로 발행한다.
# 배포본은 서버 없이 동작하는 정적(서버리스) 모드: 시뮬레이션이 브라우저에서 구동되고
# 같은 브라우저의 여러 창이 BroadcastChannel 로 동기화된다.
set -euo pipefail
cd "$(dirname "$0")/.."

node tools/gen-sim-web.js

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cp -r public/. "$TMP"/
echo 'window.TMS_STATIC = true;' > "$TMP/static-flag.js"
touch "$TMP/.nojekyll"

IDX="$(mktemp)"
export GIT_INDEX_FILE="$IDX"
git read-tree --empty
git --work-tree="$TMP" add -A
TREE="$(git write-tree)"
unset GIT_INDEX_FILE
rm -f "$IDX"

COMMIT="$(git commit-tree "$TREE" -m "Deploy static demo to GitHub Pages

Generated by tools/deploy-pages.sh from public/ (serverless mode).")"
git push -f origin "$COMMIT:refs/heads/gh-pages"

echo ""
echo "배포 완료 → https://tkdgusqkr.github.io/meatbox-demo/"
echo "(첫 배포는 GitHub Pages 활성화까지 1~2분 걸릴 수 있습니다)"
